/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package quiz.server

import db.DatabaseFactory
import db.dao.AnswerDAO
import db.dao.QuestionDAO
import db.repository.QuizRepositoryImpl
import org.koin.core.context.GlobalContext.startKoin
import org.koin.dsl.module
import quiz.server.repository.QuizRepository

fun main() {
    startKoin {
        modules(appModule)
    }

    DatabaseFactory.init()

    startServer()
}

val appModule = module {
    single<QuizRepository> { QuizRepositoryImpl(get(), get()) }

    single{ QuestionDAO() }
    single{ AnswerDAO() }
}