/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package quiz.server

class App {
    val greeting: String
        get() {
            return "Hello from model!"
        }
}

fun main() {
    println(App().greeting)
}
